language: python
dist: bionic

arch:
  - amd64

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  directories:
    - $HOME/.cache/wpssdk
    - $HOME/.cache/pip

os:
  - linux

addons:
  apt:
    update: true
    packages:
    - g++
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - qt5-default

before_install:
  - test -d "$HOME/.cache/wpssdk" || mkdir -p "$HOME/.cache/wpssdk"
  - test -f "$HOME/.cache/wpssdk/wps.deb" || wget http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/9080/wps-office_11.1.0.9080.XA_amd64.deb -O $HOME/.cache/wpssdk/wps.deb
  - dpkg -l wps-office || sudo dpkg -i $HOME/.cache/wpssdk/wps.deb

install:
  - pip install sip

script:
  - sip-wheel --verbose

deploy:
  provider: pypi
  user: __token__
  password:
      secure: LTEgsspIK69SMt/v8rEzKTnhUSRkB63/Giq6DI8zT2XU24CSGrfcvkNrd16j39EDea7WCZ8x9Oa9XVVYIKJgkG7yOZDa2jG4AF4pToX/QRAY/+v80XyhWnWr2cCIkbgwu8eAOdp8QVrHBz4uMyJjyXgNtX7pF8jkHHwXTNuYoJVAFfR7SO1eZaQ0Xt8UEnz3YKTtal17DZs67T764+p5HY7Fid0bbTE65niHu7C/h+vZdSGEFv3xm19IpSsS1OS/g+KPYN8v3aVLTz+VVCmYV4JlCDFYqG7F0uJN42bDdV36fZMwsf/m0kwl0PFg4UsdIW3HHKj0m8Oer+9scqPl58nzHGZJWAkGGeutCscNTX6DTrAsM0P7gLXq2dWD80ANXNnaK8vy3IwXZELhw2zl8X0GFet5PUt+FSS5xWAWlup7aJCSlWlvplHlDp4mJJWG6oAPoERhYt1+Fn0C+7a+1Ka3wFdgNAzOcM0oF9R5f/IXvJ8okdBkSOq5bsyo7jZU+LhBs1R7nXGXV+LkOpaiSg3rB/TECqnTHXrNSDhLg/wjT0YZjR8c5wMLrJYmwMnlqsLSUPPzkejLbHJuE5KgBOrlRcjw+8vXdb/auIkd2Tvtjkx8gRplzGf2khm+AsVHJ6ATCYSqUSIrvufNDysTbAk0B02ToSO7ZmpVPxJVwgI=
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
  skip_existing: true
