language: python
sudo: required
dist: bionic

arch:
  - amd64

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux

addons:
  apt:
    update: true
    packages:
    - sip-dev
    - python3-sip-dev
    - g++
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - wget

before_install:
  - wget http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/9080/wps-office_11.1.0.9080.XA_amd64.deb
  - sudo dpkg -i wps-office_11.1.0.9080.XA_amd64.deb

script:
  - python3 configure.py
