language: python
dist: bionic

arch:
  - amd64

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  directories:
    - $HOME/.cache/wpssdk
    - $HOME/.cache/pip

os:
  - linux

addons:
  apt:
    update: true
    packages:
    - g++
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - qt5-default

before_install:
  - test -d "$HOME/.cache/wpssdk" || mkdir -p "$HOME/.cache/wpssdk"
  - test -f "$HOME/.cache/wpssdk/wps.deb" || wget http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/9080/wps-office_11.1.0.9080.XA_amd64.deb -O $HOME/.cache/wpssdk/wps.deb
  - dpkg -l wps-office || sudo dpkg -i $HOME/.cache/wpssdk/wps.deb

install:
  - pip install sip

script:
  - sip-wheel --verbose
