language: python
dist: xenial

arch:
  - amd64

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

cache:
  directories:
    - $HOME/.cache/wpssdk
    - $HOME/.cache/pip

os:
  - linux

addons:
  apt:
    update: true
    packages:
    - g++
    - qtbase5-dev
    - qt5-default

before_install:
  - test -d "$HOME/.cache/wpssdk" || mkdir -p "$HOME/.cache/wpssdk"
  - test -f "$HOME/.cache/wpssdk/wps.deb" || wget http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/9711/wps-office_11.1.0.9711.XA_amd64.deb -O $HOME/.cache/wpssdk/wps.deb
  - dpkg -l wps-office || sudo dpkg -i $HOME/.cache/wpssdk/wps.deb

install:
  - pip install sip

script:
  - rm -fr .git .gitigore .vscode .travis.yml
  - sip-sdist
  - sip-wheel --verbose
  - mkdir dist
  - mv pywpsrpc-*.tar.gz dist
  - mv pywpsrpc-*.whl dist

deploy:
  provider: pypi
  user: __token__
  password:
      secure: XDtD8vqOXZ9qTXfY4x5m4Ql9cfK0YCdzTVTzR139EvsO75kpKSOb/adAiHOpSRk7G5WNdswoSanXHFoeYKJUiyqeoGuwTU+7h9GkJsrlQogpkNx2aykKApa6Wh7rVQ3PXJt9is6Ec3QQo4Aa4V4kacqqar/d8OWcci9p2HeZ36GKm23Bwhm7GF977n2jlZkLOCsITWoUsRJOVehlSMUitF+ZUOKOyXrngShYvJP3/vzVFDY62evxOQFhTOYVgh2YRvVbxhKXFdoRgQLb4SztOdLREvwNYdM88Pq5ui/ffpwtbKlCWp0su6odlkTezUZIf6s+6r5bUg1JLMhJbyBMlhS1l+vuo7xdwYE5snCT7SBiehP+xbSGqgsB9UX6ia8bV0l8U1oYrZ4zCPAG6TOE2EH39A3T6eEQbVTY5hy/ihTqKYkfN4Arkzb8XbwmZvOKos06pjE5jmiU4H5ZBRA6AbhgmTDJwyY5SU2s146gj5xT2EU1JqLw2o8TWLqcQtr8ZG5Maaskv0J4e0pwH2XvqDpC5ttBCzj16N7ECeI41bRi+BnNlFj7jEHybhfqvGp42h9BIb84PNsuySnEAiMA/V+mE4VZh2ozpTTrRg4sUyaFRAnlYuigDJuJ6QhekkYqalZaxGp6bNi6BcsROzv3mM0/K6B2ogWP58DyIGcXVv0=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
